eps :
  type : "linear"
  fixed : 
    eps : 0.1
  linear : 
    start : 1
    end : 0.01
  annealing : 
---
model:
  activation : "ReLU"
  dueling : False
---
train:
  total_steps : 100000
  replay_size : 100000
  gamma : 0.99
  update_interval : 2500 # Target network update interval
  max_grad : 20 # Gradient clipping
  double_dqn : False

  batch_size: 128
  optimizer: 'adam'
  adam: 0.001
  adabound:
    initial: 0.001
    final: 0.05
  frame_num: 128
  summary_interval: 10
  validation_interval: 100
  checkpoint_interval: 1000
---
scheduler: # Plateau, oneCycle, None
  type: 'Plateau'
  oneCycle:
    max_lr: 0.0001
  Plateau:
    mode: 'min'
    patience: 2
    factor: 0.5
    min_lr: 0.000005
---
  log:
    root: '/home/nas/user/kbh/KungFuMaster'